### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by woliveiras**
Add instalation mode

### CODE REVIEW

**Comment by mrodalgaard** [comment]
Thank you @woliveiras. Do you mind adding this as a one-liner under the "Todo Show Package" section instead, just above the screenshot?

**Comment by woliveiras** [comment]
Like this @mrodalgaard? :)

**Comment by mrodalgaard** [comment]
No, but closer :).

I added it to the readme in 804cced598daceb1c5f870ae87a241bbf31e2f17

**Comment by woliveiras** [comment]
Aaah, great @mrodalgaard! Now i understand. Sorry. :smile:

**Pull request closed without merging**
